#pragma once
#include <iostream>
#include <vector>
#include <map>
#include <string>
#include <cstdio>
#include <windows.graphics.h>
#include <Windows.h>
#include <mmsystem.h>
#include <filesystem>
#include <random>
#include <codecvt>
#include <cwchar>
#include <locale>
#include <memory>
#pragma comment(lib,"winmm.lib")